services:
  backend:
    environment:
      NODE_ENV: development
      PORT: 3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true

  frontend:
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_WS_URL: ws://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    stdin_open: true
    tty: true